name: Run OPA Tests

on: [push]

jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v1
      with:
        version: latest

    - name: Run OPA Tests
      run: opa test ./rego/*.rego -v

    - name: Validate Kubernetes Manifest
      run: opa eval --data ./rego/all.rego --input ./namespace.json "data.kubernetes.admission.deny"
