name: Rego Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup OPA
      run: |
        curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
        chmod 755 ./opa

    - name: Validate Rego
      run: ./opa check ./rego/all.rego

    - name: Test Rego
      run: ./opa test ./rego/  # replace with your actual rego test directory if you have tests

    - name: Process JSON
      run: |
        sudo apt-get install -y jq
        jq . ./rego/all.json
