name: Rego Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Setup OPA
      run: |
        curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
        chmod 755 ./opa

    - name: Validate Rego
      run: ./opa check ./rego/all.rego

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Process JSON
      run: jq . ./rego/all.json
